window.i18n = {
  be: {nav_about:'Пра нас',nav_programs:'Праграмы',nav_who:'Для каго',nav_apply:'Падаць заяўку',logo_sub:'Канцэрн LABS67',
    title: 'SLYAH.AI — Інстытут клінічных стандартаў · LABS67',
    nav_cta: 'Падаць заяўку',
        hero_h1_1: 'Інстытут клінічных',
    hero_h1_2: 'стандартаў будучыні',
    hero_sub: 'Не павышэнне кваліфікацыі — поўная перазагрузка клінічнага мыслення. Усе ўрачы LABS67 праходзяць праз SLYAH.AI.',
    back: '← LABS67',
    hero_tag:'// SLYAH.AI · Канцэрн LABS67',
    btn1:'// Падаць заяўку',
    btn2:'Праграмы →',
    stat1:'Трэкі',
    stat2:'Інструменты',
    stat3:'Стандарт',
    man_tag:'// Наш падыход',
    man_title:'Не курс.<br><span class="ac">Перазагрузка.</span>',
    man_quote:'«Кожны спецыяліст канцэрна LABS67 прайшоў праз SLYAH.AI. Гэта не опцыя — гэта стандарт.»',
    pr1_num:'ПРЫНЦЫП_01',
    pr1_t:'Пацыент — цэнтр сістэмы',
    pr2_num:'ПРЫНЦЫП_02',
    pr2_t:'ІІ — інструмент, не замена',
    pr3_num:'ПРЫНЦЫП_03',
    pr3_t:'Стандарт — усюды аднолькавы',
    pr4_num:'ПРЫНЦЫП_04',
    pr4_t:'Даследаванне — частка практыкі',
    trk_tag:'// Праграмы',
    trk_title:'Тры <span class="ac">трэкі</span>',
    trk_lead:'Кожны трэк — асобная праграма з выразнымі мэтамі і вынікамі.',
    t1_title:'Clinical Reboot',
    t2_title:'AI Integration Cert',
    t3_title:'R&D Lab',
    man_body:'Мы стварылі інстытут, таму што добрых урачоў мала — не па ведах, а па падыходзе. SLYAH.AI мяняе тое, як спецыяліст думае пра пацыента, пра працэс і пра тэхналогіі.',
    pr1_d:'Усе пратаколы будуюцца вакол вопыту пацыента. Не вакол зручнасці ўрача або клінікі.',
    pr2_d:'Урач вырашае. ІІ забяспечвае дакладнасць, хуткасць і дакументаванне. Мы вучым працаваць з гэтым сімбіёзам.',
    pr3_d:'Пацыент у любой клініцы канцэрна атрымлівае ідэнтычны ўзровень клопату. SLYAH.AI гэта гарантуе.',
    pr4_d:'Лепшыя спецыялісты ўдзельнічаюць у распрацоўцы новых пратаколаў. Мы растзём разам з нашымі ўрачамі.',
    t1_d:'Поўная перазагрузка клінічных пратаколаў. Стандарты працы з пацыентам, дакументаванне, узаемадзеянне з ІІ-сістэмай клінікі. Абавязковы для ўсіх урачоў канцэрна.',
    t1_dur:'Працягласць: 2 тыдні · Ачна + практыка',
    t2_d:'Сертыфікацыя па працы з ІІ-інструментамі канцэрна. Галасавыя пратаколы, аналіз здымкаў, інтэрфейс асістэнта. Практыка на рэальным абсталяванні LABS67.',
    t2_dur:'Працягласць: 1 тыдзень · Практыка',
    t3_d:'Для лідараў меркавання і спецыялістаў, гатовых удзельнічаць у распрацоўцы новых пратаколаў. Клінічныя выпрабаванні, навуковыя публікацыі.',
    t3_dur:'Працягласць: Па праекце · Пастаяннны ўдзел',
    who_tag:'// Для каго',
    who_title:'Хто прыходзіць у <span class="ac">SLYAH.AI</span>',
    who1_t:'Урачы клінік LABS67',
    who1_d:'Абавязковая сертыфікацыя для ўсіх спецыялістаў, якія працуюць пад брэндамі канцэрна.',
    who2_t:'Каманды франчайзі',
    who2_d:'Партнёры LADZA.AI праходзяць SLYAH.AI перад адкрыццём — гэта частка стандарту канцэрна.',
    who3_t:'Незалежныя спецыялісты',
    who3_d:'Урачы, якія хочуць працаваць інакш — з тэхналогіямі, па стандартах сусветнага ўзроўню.',
    who4_t:'Даследчыкі',
    who4_d:'Спецыялісты з вопытам, гатовыя ўдзельнічаць у R&D і фарміраванні новых клінічных пратаколаў.',
    sb1_lbl:'// Гарантыя канцэрна',
    sb1_t:'Сертыфікат SLYAH.AI — гэта знак таго, што спецыяліст працуе па стандартах LABS67.',
    sb1_s:'Пацыенты ведаюць: калі ўрач сертыфікаваны SLYAH.AI — яны ў надзейных руках. Незалежна ад таго, у якім горадзе або краіне знаходзіцца клініка.',
    sb2_lbl:'// Для партнёраў LADZA.AI',
    sb2_t:'Навучанне каманды ўваходзіць у пакет падтрымкі пры адкрыцці клінікі.',
    sb2_s:'Франчайзі не займаюцца пошукам і навучаннем персаналу ў адзіночку — SLYAH.AI закрывае гэтую задачу цалкам.',
    app_tag:'// Падаць заяўку',
    app_title:'Пачніце <span class="ac">зараз</span>',
    app_lead:'Набор — па заяўцы. Прыярытэт: партнёры канцэрна і незалежныя спецыялісты з вопытам ад 2 гадоў.',
    form_title:'// ЗАЯЎКА НА НАВУЧАННЕ',
    form_btn:'// АДПРАВІЦЬ ЗАЯЎКУ →',
    footer_sub:'Канцэрн LABS67',
    track1_tag:'ТРЭК_01 · АСНОЎНЫ',track2_tag:'ТРЭК_02 · ТЭХНАЛАГІЧНЫ',track3_tag:'ТРЭК_03 · ДАСЛЕДЧЫ',
  },
  uk: {nav_about:'Про нас',nav_programs:'Програми',nav_who:'Для кого',nav_apply:'Подати заявку',logo_sub:'Концерн LABS67',
    title: 'SLYAH.AI — Інститут клінічних стандартів · LABS67',
    nav_cta: 'Подати заявку',
        hero_h1_1: 'Інститут клінічних',
    hero_h1_2: 'стандартів майбутнього',
    hero_sub: 'Не підвищення кваліфікації — повне перезавантаження клінічного мислення. Всі лікарі LABS67 проходять через SLYAH.AI.',
    back: '← LABS67',
    hero_tag:'// SLYAH.AI · Концерн LABS67',
    btn1:'// Подати заявку',
    btn2:'Програми →',
    stat1:'Треки',
    stat2:'Інструменти',
    stat3:'Стандарт',
    man_tag:'// Наш підхід',
    man_title:'Не курс.<br><span class="ac">Перезавантаження.</span>',
    man_quote:'«Кожен фахівець концерну LABS67 пройшов через SLYAH.AI. Це не опція — це стандарт.»',
    pr1_num:'ПРИНЦИП_01',
    pr1_t:'Пацієнт — центр системи',
    pr2_num:'ПРИНЦИП_02',
    pr2_t:'ШІ — інструмент, не заміна',
    pr3_num:'ПРИНЦИП_03',
    pr3_t:'Стандарт — скрізь однаковий',
    pr4_num:'ПРИНЦИП_04',
    pr4_t:'Дослідження — частина практики',
    trk_tag:'// Програми',
    trk_title:'Три <span class="ac">треки</span>',
    trk_lead:'Кожен трек — окрема програма з чіткими цілями та результатами.',
    t1_title:'Clinical Reboot',
    t2_title:'AI Integration Cert',
    t3_title:'R&D Lab',
    man_body:'Ми створили інститут, тому що хороших лікарів мало — не за знаннями, а за підходом. SLYAH.AI змінює те, як фахівець думає про пацієнта, про процес і про технології.',
    pr1_d:'Всі протоколи будуються навколо досвіду пацієнта. Не навколо зручності лікаря або клініки.',
    pr2_d:'Лікар вирішує. ШІ забезпечує точність, швидкість і документування. Ми навчаємо працювати з цим симбіозом.',
    pr3_d:'Пацієнт у будь-якій клініці концерну отримує ідентичний рівень турботи. SLYAH.AI це гарантує.',
    pr4_d:'Кращі фахівці беруть участь у розробці нових протоколів. Ми ростемо разом з нашими лікарями.',
    t1_d:'Повне перезавантаження клінічних протоколів. Стандарти роботи з пацієнтом, документування, взаємодія з ШІ-системою клініки. Обов\'язковий для всіх лікарів концерну.',
    t1_dur:'Тривалість: 2 тижні · Очно + практика',
    t2_d:'Сертифікація з роботи з ШІ-інструментами концерну. Голосові протоколи, аналіз знімків, інтерфейс асистента. Практика на реальному обладнанні LABS67.',
    t2_dur:'Тривалість: 1 тиждень · Практика',
    t3_d:'Для лідерів думок і фахівців, готових брати участь у розробці нових протоколів. Клінічні випробування, наукові публікації.',
    t3_dur:'Тривалість: За проектом · Постійна участь',
    who_tag:'// Для кого',
    who_title:'Хто приходить в <span class="ac">SLYAH.AI</span>',
    who1_t:'Лікарі клінік LABS67',
    who1_d:'Обов\'язкова сертифікація для всіх фахівців, що працюють під брендами концерну.',
    who2_t:'Команди франчайзі',
    who2_d:'Партнери LADZA.AI проходять SLYAH.AI перед відкриттям — це частина стандарту концерну.',
    who3_t:'Незалежні фахівці',
    who3_d:'Лікарі, які хочуть працювати інакше — з технологіями, за стандартами світового рівня.',
    who4_t:'Дослідники',
    who4_d:'Фахівці з досвідом, готові брати участь у R&D та формуванні нових клінічних протоколів.',
    sb1_lbl:'// Гарантія концерну',
    sb1_t:'Сертифікат SLYAH.AI — це знак того, що фахівець працює за стандартами LABS67.',
    sb1_s:'Пацієнти знають: якщо лікар сертифікований SLYAH.AI — вони в надійних руках. Незалежно від міста або країни.',
    sb2_lbl:'// Для партнерів LADZA.AI',
    sb2_t:'Навчання команди входить до пакету підтримки при відкритті клініки.',
    sb2_s:'Франчайзі не займаються пошуком і навчанням персоналу поодинці — SLYAH.AI закриває це завдання повністю.',
    app_tag:'// Подати заявку',
    app_title:'Почніть <span class="ac">зараз</span>',
    app_lead:'Набір — за заявкою. Пріоритет: партнери концерну та незалежні фахівці з досвідом від 2 років.',
    form_title:'// ЗАЯВКА НА НАВЧАННЯ',
    form_btn:'// НАДІСЛАТИ ЗАЯВКУ →',
    footer_sub:'Концерн LABS67',
    track1_tag:'ТРЕК_01 · ОСНОВНИЙ',track2_tag:'ТРЕК_02 · ТЕХНОЛОГІЧНИЙ',track3_tag:'ТРЕК_03 · ДОСЛІДНИЦЬКИЙ',
  },
  en: {nav_about:'About',nav_programs:'Programs',nav_who:'For who',nav_apply:'Apply',logo_sub:'LABS67 Concern',
    title: 'SLYAH.AI — Institute of Clinical Standards · LABS67',
    nav_cta: 'Apply',
        hero_h1_1: 'Institute of Clinical',
    hero_h1_2: 'Standards of the Future',
    hero_sub: 'Not qualification upgrading — a complete reboot of clinical thinking. All LABS67 doctors go through SLYAH.AI.',
    back: '← LABS67',
    hero_tag:'// SLYAH.AI · LABS67 Concern',
    btn1:'// Apply',
    btn2:'Programmes →',
    stat1:'Tracks',
    stat2:'Tools',
    stat3:'Standard',
    man_tag:'// Our approach',
    man_title:'Not a course.<br><span class="ac">A reboot.</span>',
    man_quote:'«Every specialist of the LABS67 concern has been through SLYAH.AI. This is not an option — it\'s a standard.»',
    pr1_num:'PRINCIPLE_01',
    pr1_t:'Patient — centre of the system',
    pr2_num:'PRINCIPLE_02',
    pr2_t:'AI — a tool, not a replacement',
    pr3_num:'PRINCIPLE_03',
    pr3_t:'Standard — identical everywhere',
    pr4_num:'PRINCIPLE_04',
    pr4_t:'Research — part of practice',
    trk_tag:'// Programmes',
    trk_title:'Three <span class="ac">tracks</span>',
    trk_lead:'Each track is a separate programme with clear goals and outcomes.',
    t1_title:'Clinical Reboot',
    t2_title:'AI Integration Cert',
    t3_title:'R&D Lab',
    man_body:'We created the institute because good doctors are rare — not in knowledge, but in approach. SLYAH.AI changes how a specialist thinks about the patient, the process and the technology.',
    pr1_d:'All protocols are built around the patient experience. Not around the convenience of the doctor or clinic.',
    pr2_d:'The doctor decides. AI ensures accuracy, speed and documentation. We teach working with this symbiosis.',
    pr3_d:'A patient at any clinic in the concern receives an identical level of care. SLYAH.AI guarantees this.',
    pr4_d:'The best specialists participate in developing new protocols. We grow together with our doctors.',
    t1_d:'Full reboot of clinical protocols. Standards of patient care, documentation, interaction with the clinic AI system. Mandatory for all concern doctors.',
    t1_dur:'Duration: 2 weeks · In-person + practice',
    t2_d:'Certification for working with the concern\'s AI tools. Voice protocols, image analysis, assistant interface. Practice on real LABS67 equipment.',
    t2_dur:'Duration: 1 week · Practice',
    t3_d:'For opinion leaders and specialists ready to participate in developing new protocols. Clinical trials, scientific publications, shaping future standards.',
    t3_dur:'Duration: Per project · Ongoing participation',
    who_tag:'// Who it\'s for',
    who_title:'Who comes to <span class="ac">SLYAH.AI</span>',
    who1_t:'LABS67 clinic doctors',
    who1_d:'Mandatory certification for all specialists working under the concern\'s brands.',
    who2_t:'Franchise teams',
    who2_d:'LADZA.AI partners go through SLYAH.AI before opening — it is part of the concern standard.',
    who3_t:'Independent specialists',
    who3_d:'Doctors who want to work differently — with technology, to world-class standards.',
    who4_t:'Researchers',
    who4_d:'Experienced specialists ready to participate in R&D and shaping new clinical protocols.',
    sb1_lbl:'// Concern guarantee',
    sb1_t:'An SLYAH.AI certificate is a sign that the specialist works to LABS67 standards.',
    sb1_s:'Patients know: if a doctor is SLYAH.AI-certified — they are in safe hands. Regardless of which city or country the clinic is in.',
    sb2_lbl:'// For LADZA.AI partners',
    sb2_t:'Team training is included in the support package when opening a clinic.',
    sb2_s:'Franchisees don\'t handle recruitment and training alone — SLYAH.AI closes this task completely.',
    app_tag:'// Apply',
    app_title:'Start <span class="ac">now</span>',
    app_lead:'Enrolment is by application. Priority: concern partners and independent specialists with 2+ years experience.',
    form_title:'// APPLICATION FOR TRAINING',
    form_btn:'// SUBMIT APPLICATION →',
    footer_sub:'LABS67 Concern',
    track1_tag:'TRACK_01 · CORE',track2_tag:'TRACK_02 · TECHNOLOGY',track3_tag:'TRACK_03 · RESEARCH',
  },
  pl: {nav_about:'O nas',nav_programs:'Programy',nav_who:'Dla kogo',nav_apply:'Aplikuj',logo_sub:'Koncern LABS67',
    title: 'SLYAH.AI — Instytut Standardów Klinicznych · LABS67',
    nav_cta: 'Aplikuj',
        hero_h1_1: 'Instytut Kliniczny',
    hero_h1_2: 'Standardów Przyszłości',
    hero_sub: 'Nie podnoszenie kwalifikacji — pełny restart myślenia klinicznego. Wszyscy lekarze LABS67 przechodzą przez SLYAH.AI.',
    back: '← LABS67',
    hero_tag:'// SLYAH.AI · Koncern LABS67',
    btn1:'// Złóż wniosek',
    btn2:'Programy →',
    stat1:'Ścieżki',
    stat2:'Narzędzia',
    stat3:'Standard',
    man_tag:'// Nasze podejście',
    man_title:'Nie kurs.<br><span class="ac">Restart.</span>',
    man_quote:'«Każdy specjalista koncernu LABS67 przeszedł przez SLYAH.AI. To nie opcja — to standard.»',
    pr1_num:'ZASADA_01',
    pr1_t:'Pacjent — centrum systemu',
    pr2_num:'ZASADA_02',
    pr2_t:'AI — narzędzie, nie zamiennik',
    pr3_num:'ZASADA_03',
    pr3_t:'Standard — wszędzie jednakowy',
    pr4_num:'ZASADA_04',
    pr4_t:'Badania — część praktyki',
    trk_tag:'// Programy',
    trk_title:'Trzy <span class="ac">ścieżki</span>',
    trk_lead:'Każda ścieżka to oddzielny program z jasno określonymi celami i rezultatami.',
    t1_title:'Clinical Reboot',
    t2_title:'AI Integration Cert',
    t3_title:'R&D Lab',
    man_body:'Stworzyliśmy instytut, bo dobrych lekarzy jest mało — nie pod względem wiedzy, lecz podejścia. SLYAH.AI zmienia sposób, w jaki specjalista myśli o pacjencie, procesie i technologii.',
    pr1_d:'Wszystkie protokoły budowane są wokół doświadczenia pacjenta. Nie wokół wygody lekarza czy kliniki.',
    pr2_d:'Lekarz decyduje. AI zapewnia dokładność, szybkość i dokumentację. Uczymy pracy z tą symbiozą.',
    pr3_d:'Pacjent w każdej klinice koncernu otrzymuje identyczny poziom opieki. SLYAH.AI to gwarantuje.',
    pr4_d:'Najlepsi specjaliści uczestniczą w opracowywaniu nowych protokołów. Rozwijamy się razem z naszymi lekarzami.',
    t1_d:'Pełny restart protokołów klinicznych. Standardy pracy z pacjentem, dokumentacja, interakcja z systemem AI kliniki. Obowiązkowy dla wszystkich lekarzy koncernu.',
    t1_dur:'Czas trwania: 2 tygodnie · Stacjonarnie + praktyka',
    t2_d:'Certyfikacja z narzędzi AI koncernu. Protokoły głosowe, analiza zdjęć, interfejs asystenta. Praktyka na sprzęcie LABS67.',
    t2_dur:'Czas trwania: 1 tydzień · Praktyka',
    t3_d:'Dla liderów opinii i specjalistów gotowych do udziału w opracowywaniu nowych protokołów. Badania kliniczne, publikacje naukowe.',
    t3_dur:'Czas trwania: Według projektu · Stały udział',
    who_tag:'// Dla kogo',
    who_title:'Kto trafia do <span class="ac">SLYAH.AI</span>',
    who1_t:'Lekarze klinik LABS67',
    who1_d:'Obowiązkowa certyfikacja dla wszystkich specjalistów pracujących pod markami koncernu.',
    who2_t:'Zespoły franczyzobiorców',
    who2_d:'Partnerzy LADZA.AI przechodzą SLYAH.AI przed otwarciem — to część standardu koncernu.',
    who3_t:'Niezależni specjaliści',
    who3_d:'Lekarze, którzy chcą pracować inaczej — z technologią, według standardów światowego poziomu.',
    who4_t:'Badacze',
    who4_d:'Specjaliści z doświadczeniem, gotowi uczestniczyć w R&D i tworzeniu nowych protokołów klinicznych.',
    sb1_lbl:'// Gwarancja koncernu',
    sb1_t:'Certyfikat SLYAH.AI to znak, że specjalista pracuje według standardów LABS67.',
    sb1_s:'Pacjenci wiedzą: jeśli lekarz jest certyfikowany przez SLYAH.AI — są w dobrych rękach. Niezależnie od miasta czy kraju.',
    sb2_lbl:'// Dla partnerów LADZA.AI',
    sb2_t:'Szkolenie zespołu jest wliczone w pakiet wsparcia przy otwieraniu kliniki.',
    sb2_s:'Franczyzobiorcy nie zajmują się rekrutacją i szkoleniem personelu samodzielnie — SLYAH.AI w pełni zamyka to zadanie.',
    app_tag:'// Złóż wniosek',
    app_title:'Zacznij <span class="ac">teraz</span>',
    app_lead:'Nabór odbywa się na podstawie wniosku. Priorytet: partnerzy koncernu i niezależni specjaliści z 2+ latami doświadczenia.',
    form_title:'// WNIOSEK O SZKOLENIE',
    form_btn:'// WYŚLIJ WNIOSEK →',
    footer_sub:'Koncern LABS67',
    track1_tag:'ŚCIEŻKA_01 · PODSTAWOWA',track2_tag:'ŚCIEŻKA_02 · TECHNOLOGICZNA',track3_tag:'ŚCIEŻKA_03 · BADAWCZA',
  },
  fr: {nav_about:'À propos',nav_programs:'Programmes',nav_who:'Pour qui',nav_apply:'Postuler',logo_sub:'Groupe LABS67',
    title: 'SLYAH.AI — Institut des Standards Cliniques · LABS67',
    nav_cta: 'Postuler',
        hero_h1_1: 'Institut des Standards',
    hero_h1_2: 'Cliniques du Futur',
    hero_sub: 'Pas une mise à niveau — un redémarrage complet de la pensée clinique. Tous les médecins LABS67 passent par SLYAH.AI.',
    back: '← LABS67',
    hero_tag:'// SLYAH.AI · Groupe LABS67',
    btn1:'// Postuler',
    btn2:'Programmes →',
    stat1:'Parcours',
    stat2:'Outils',
    stat3:'Standard',
    man_tag:'// Notre approche',
    man_title:'Pas un cours.<br><span class="ac">Un reboot.</span>',
    man_quote:'«Chaque spécialiste du groupe LABS67 est passé par SLYAH.AI. Ce n\'est pas une option — c\'est un standard.»',
    pr1_num:'PRINCIPE_01',
    pr1_t:'Le patient — au centre du système',
    pr2_num:'PRINCIPE_02',
    pr2_t:'L\'IA — un outil, pas un remplaçant',
    pr3_num:'PRINCIPE_03',
    pr3_t:'Le standard — identique partout',
    pr4_num:'PRINCIPE_04',
    pr4_t:'La recherche — partie de la pratique',
    trk_tag:'// Programmes',
    trk_title:'Trois <span class="ac">parcours</span>',
    trk_lead:'Chaque parcours est un programme distinct avec des objectifs et résultats clairs.',
    t1_title:'Clinical Reboot',
    t2_title:'AI Integration Cert',
    t3_title:'R&D Lab',
    man_body:'Nous avons créé l\'institut parce que les bons médecins sont rares — non par manque de connaissances, mais d\'approche. SLYAH.AI change la façon dont le spécialiste pense au patient, au processus et à la technologie.',
    pr1_d:'Tous les protocoles sont construits autour de l\'expérience du patient. Pas autour de la commodité du médecin ou de la clinique.',
    pr2_d:'Le médecin décide. L\'IA assure précision, rapidité et documentation. Nous enseignons à travailler avec cette symbiose.',
    pr3_d:'Un patient dans n\'importe quelle clinique du groupe reçoit un niveau de soins identique. SLYAH.AI le garantit.',
    pr4_d:'Les meilleurs spécialistes participent au développement de nouveaux protocoles. Nous grandissons avec nos médecins.',
    t1_d:'Redémarrage complet des protocoles cliniques. Standards de prise en charge, documentation, interaction avec le système IA. Obligatoire pour tous les médecins du groupe.',
    t1_dur:'Durée: 2 semaines · Présentiel + pratique',
    t2_d:'Certification sur les outils IA du groupe. Protocoles vocaux, analyse d\'images, interface assistant. Pratique sur équipement LABS67.',
    t2_dur:'Durée: 1 semaine · Pratique',
    t3_d:'Pour les leaders d\'opinion et spécialistes prêts à développer de nouveaux protocoles. Essais cliniques, publications scientifiques.',
    t3_dur:'Durée: Par projet · Participation continue',
    who_tag:'// Pour qui',
    who_title:'Qui vient à <span class="ac">SLYAH.AI</span>',
    who1_t:'Médecins des cliniques LABS67',
    who1_d:'Certification obligatoire pour tous les spécialistes travaillant sous les marques du groupe.',
    who2_t:'Équipes franchisées',
    who2_d:'Les partenaires LADZA.AI passent par SLYAH.AI avant l\'ouverture — c\'est un standard du groupe.',
    who3_t:'Spécialistes indépendants',
    who3_d:'Des médecins qui veulent travailler autrement — avec la technologie, selon des standards mondiaux.',
    who4_t:'Chercheurs',
    who4_d:'Spécialistes expérimentés prêts à participer à la R&D et à l\'élaboration de nouveaux protocoles cliniques.',
    sb1_lbl:'// Garantie du groupe',
    sb1_t:'Le certificat SLYAH.AI signifie que le spécialiste travaille selon les standards LABS67.',
    sb1_s:'Les patients savent: si un médecin est certifié SLYAH.AI — ils sont entre de bonnes mains. Peu importe la ville ou le pays.',
    sb2_lbl:'// Pour les partenaires LADZA.AI',
    sb2_t:'La formation de l\'équipe est incluse dans le package de soutien à l\'ouverture.',
    sb2_s:'Les franchisés ne gèrent pas seuls le recrutement et la formation — SLYAH.AI s\'en charge entièrement.',
    app_tag:'// Postuler',
    app_title:'Commencez <span class="ac">maintenant</span>',
    app_lead:'Inscription sur candidature. Priorité: partenaires du groupe et spécialistes indépendants avec 2+ ans d\'expérience.',
    form_title:'// CANDIDATURE DE FORMATION',
    form_btn:'// ENVOYER LA CANDIDATURE →',
    footer_sub:'Groupe LABS67',
    track1_tag:'PISTE_01 · FONDAMENTAL',track2_tag:'PISTE_02 · TECHNOLOGIQUE',track3_tag:'PISTE_03 · RECHERCHE',
  },
  de: {nav_about:'Über uns',nav_programs:'Programme',nav_who:'Für wen',nav_apply:'Bewerben',logo_sub:'LABS67 Konzern',
    title: 'SLYAH.AI — Institut für klinische Standards · LABS67',
    nav_cta: 'Bewerben',
        hero_h1_1: 'Institut für klinische',
    hero_h1_2: 'Standards der Zukunft',
    hero_sub: 'Keine Qualifikationsaufwertung — ein vollständiger Neustart des klinischen Denkens. Alle LABS67-Ärzte durchlaufen SLYAH.AI.',
    back: '← LABS67',
    hero_tag:'// SLYAH.AI · LABS67 Konzern',
    btn1:'// Bewerben',
    btn2:'Programme →',
    stat1:'Tracks',
    stat2:'Werkzeuge',
    stat3:'Standard',
    man_tag:'// Unser Ansatz',
    man_title:'Kein Kurs.<br><span class="ac">Ein Neustart.</span>',
    man_quote:'«Jeder Spezialist des LABS67-Konzerns hat SLYAH.AI durchlaufen. Das ist keine Option — es ist ein Standard.»',
    pr1_num:'PRINZIP_01',
    pr1_t:'Patient — Zentrum des Systems',
    pr2_num:'PRINZIP_02',
    pr2_t:'KI — ein Werkzeug, kein Ersatz',
    pr3_num:'PRINZIP_03',
    pr3_t:'Standard — überall gleich',
    pr4_num:'PRINZIP_04',
    pr4_t:'Forschung — Teil der Praxis',
    trk_tag:'// Programme',
    trk_title:'Drei <span class="ac">Tracks</span>',
    trk_lead:'Jeder Track ist ein eigenständiges Programm mit klaren Zielen und Ergebnissen.',
    t1_title:'Clinical Reboot',
    t2_title:'AI Integration Cert',
    t3_title:'R&D Lab',
    man_body:'Wir haben das Institut gegründet, weil es gute Ärzte selten gibt — nicht wegen fehlenden Wissens, sondern wegen des Ansatzes. SLYAH.AI verändert, wie ein Spezialist über den Patienten, den Prozess und die Technologie denkt.',
    pr1_d:'Alle Protokolle sind um die Patientenerfahrung herum aufgebaut. Nicht um die Bequemlichkeit des Arztes oder der Klinik.',
    pr2_d:'Der Arzt entscheidet. KI sorgt für Genauigkeit, Geschwindigkeit und Dokumentation. Wir lehren die Arbeit mit dieser Symbiose.',
    pr3_d:'Ein Patient in jeder Klinik des Konzerns erhält ein identisches Betreuungsniveau. SLYAH.AI garantiert das.',
    pr4_d:'Die besten Spezialisten beteiligen sich an der Entwicklung neuer Protokolle. Wir wachsen gemeinsam mit unseren Ärzten.',
    t1_d:'Vollständiger Neustart klinischer Protokolle. Standards der Patientenversorgung, Dokumentation, Interaktion mit dem KI-System. Pflicht für alle Konzernärzte.',
    t1_dur:'Dauer: 2 Wochen · Präsenz + Praxis',
    t2_d:'Zertifizierung für KI-Tools des Konzerns. Sprachprotokolle, Bildanalyse, Assistenten-Interface. Praxis an echtem LABS67-Equipment.',
    t2_dur:'Dauer: 1 Woche · Praxis',
    t3_d:'Für Meinungsführer und Spezialisten, die neue Protokolle entwickeln wollen. Klinische Studien, wissenschaftliche Veröffentlichungen.',
    t3_dur:'Dauer: Projektbezogen · Dauerhafte Teilnahme',
    who_tag:'// Für wen',
    who_title:'Wer kommt zu <span class="ac">SLYAH.AI</span>',
    who1_t:'LABS67-Klinikärzte',
    who1_d:'Pflicht-Zertifizierung für alle Spezialisten, die unter den Marken des Konzerns arbeiten.',
    who2_t:'Franchise-Teams',
    who2_d:'LADZA.AI-Partner durchlaufen SLYAH.AI vor der Eröffnung — es ist Teil des Konzernstandards.',
    who3_t:'Unabhängige Spezialisten',
    who3_d:'Ärzte, die anders arbeiten wollen — mit Technologie, nach Weltklasse-Standards.',
    who4_t:'Forscher',
    who4_d:'Erfahrene Spezialisten, die bereit sind, an R&D und der Entwicklung neuer klinischer Protokolle teilzunehmen.',
    sb1_lbl:'// Konzerngarantie',
    sb1_t:'Ein SLYAH.AI-Zertifikat ist ein Zeichen, dass der Spezialist nach LABS67-Standards arbeitet.',
    sb1_s:'Patienten wissen: wenn ein Arzt SLYAH.AI-zertifiziert ist — sind sie in sicheren Händen. Unabhängig von Stadt oder Land.',
    sb2_lbl:'// Für LADZA.AI-Partner',
    sb2_t:'Die Teamschulung ist im Support-Paket bei der Klinik-Eröffnung enthalten.',
    sb2_s:'Franchisenehmer kümmern sich nicht allein um Rekrutierung und Schulung — SLYAH.AI schließt diese Aufgabe vollständig.',
    app_tag:'// Bewerben',
    app_title:'Jetzt <span class="ac">starten</span>',
    app_lead:'Aufnahme auf Antrag. Priorität: Konzernpartner und unabhängige Spezialisten mit 2+ Jahren Erfahrung.',
    form_title:'// BEWERBUNG FÜR SCHULUNG',
    form_btn:'// BEWERBUNG SENDEN →',
    footer_sub:'LABS67 Konzern',
    track1_tag:'TRACK_01 · GRUNDLAGEN',track2_tag:'TRACK_02 · TECHNOLOGIE',track3_tag:'TRACK_03 · FORSCHUNG',
  },
  ru: {nav_about:'О нас',nav_programs:'Программы',nav_who:'Для кого',nav_apply:'Подать заявку',logo_sub:'Концерн LABS67',
    title: 'SLYAH.AI — Институт клинических стандартов · LABS67',
    nav_cta: 'Подать заявку',
    hero_h1_1: 'Институт клинических',
    hero_h1_2: 'стандартов будущего',
    hero_sub: 'Не повышение квалификации — полная перезагрузка клинического мышления. Все врачи LABS67 проходят через SLYAH.AI.',
    back: '← LABS67',
    hero_tag:'// SLYAH.AI · Концерн LABS67',
    btn1:'// Подать заявку',
    btn2:'Программы →',
    stat1:'Трека',
    stat2:'Инструменты',
    stat3:'Стандарт',
    man_tag:'// Наш подход',
    man_title:'Не курс.<br><span class="ac">Перезагрузка.</span>',
    man_quote:'«Каждый специалист концерна LABS67 прошёл через SLYAH.AI. Это не опция — это стандарт.»',
    pr1_num:'ПРИНЦИП_01',
    pr1_t:'Пациент — центр системы',
    pr2_num:'ПРИНЦИП_02',
    pr2_t:'ИИ — инструмент, а не замена',
    pr3_num:'ПРИНЦИП_03',
    pr3_t:'Стандарт — везде одинаковый',
    pr4_num:'ПРИНЦИП_04',
    pr4_t:'Исследование — часть практики',
    trk_tag:'// Программы',
    trk_title:'Три <span class="ac">трека</span>',
    trk_lead:'Каждый трек — отдельная программа с чёткими целями и результатами.',
    t1_title:'Clinical Reboot',
    t2_title:'AI Integration Cert',
    t3_title:'R&D Lab',
    man_body:'Мы создали институт, потому что хороших врачей мало — не по знаниям, а по подходу. SLYAH.AI меняет то, как специалист думает о пациенте, о процессе и о технологиях.',
    pr1_d:'Все протоколы строятся вокруг опыта пациента. Не вокруг удобства врача или клиники.',
    pr2_d:'Врач решает. ИИ обеспечивает точность, скорость и документирование. Мы учим работать с этим симбиозом.',
    pr3_d:'Пациент в любой клинике концерна получает идентичный уровень заботы. SLYAH.AI это гарантирует.',
    pr4_d:'Лучшие специалисты участвуют в разработке новых протоколов. Мы растём вместе с нашими врачами.',
    t1_d:'Полная перезагрузка клинических протоколов. Стандарты работы с пациентом, документирование, взаимодействие с ИИ-системой клиники. Обязателен для всех врачей концерна.',
    t1_dur:'Длительность: 2 недели · Очно + практика',
    t2_d:'Сертификация по работе с ИИ-инструментами концерна. Голосовые протоколы, анализ снимков, интерфейс ассистента. Практика на реальном оборудовании LABS67.',
    t2_dur:'Длительность: 1 неделя · Практика',
    t3_d:'Для лидеров мнений и специалистов, готовых участвовать в разработке новых протоколов. Клинические испытания, научные публикации, формирование стандартов будущего.',
    t3_dur:'Длительность: По проекту · Постоянное участие',
    who_tag:'// Для кого',
    who_title:'Кто приходит в <span class="ac">SLYAH.AI</span>',
    who1_t:'Врачи клиник LABS67',
    who1_d:'Обязательная сертификация для всех специалистов, работающих под брендами концерна.',
    who2_t:'Команды франчайзи',
    who2_d:'Партнёры LADZA.AI проходят SLYAH.AI перед открытием — это часть стандарта концерна.',
    who3_t:'Независимые специалисты',
    who3_d:'Врачи, которые хотят работать иначе — с технологиями, по стандартам мирового уровня.',
    who4_t:'Исследователи',
    who4_d:'Специалисты с опытом, готовые участвовать в R&D и формировании новых клинических протоколов.',
    sb1_lbl:'// Гарантия концерна',
    sb1_t:'Сертификат SLYAH.AI — знак того, что специалист работает по стандартам LABS67.',
    sb1_s:'Пациенты знают: если врач сертифицирован SLYAH.AI — они в надёжных руках. Независимо от города или страны.',
    sb2_lbl:'// Для партнёров LADZA.AI',
    sb2_t:'Обучение команды входит в пакет поддержки при открытии клиники.',
    sb2_s:'Франчайзи не занимаются поиском и обучением персонала в одиночку — SLYAH.AI закрывает эту задачу полностью.',
    app_tag:'// Подать заявку',
    app_title:'Начните <span class="ac">сейчас</span>',
    app_lead:'Набор — по заявке. Приоритет: партнёры концерна и независимые специалисты с опытом от 2 лет.',
    form_title:'// ЗАЯВКА НА ОБУЧЕНИЕ',
    form_btn:'// ОТПРАВИТЬ ЗАЯВКУ →',
    footer_sub:'Концерн LABS67',
    track1_tag:'ТРЕК_01 · ОСНОВНОЙ',track2_tag:'ТРЕК_02 · ТЕХНОЛОГИЧЕСКИЙ',track3_tag:'ТРЕК_03 · ИССЛЕДОВАТЕЛЬСКИЙ',
  },
  es: {nav_about:'Sobre nosotros',nav_programs:'Programas',nav_who:'Para quién',nav_apply:'Solicitar',logo_sub:'Grupo LABS67',
    title: 'SLYAH.AI — Instituto de Estándares Clínicos · LABS67',
    nav_cta: 'Solicitar',
    hero_h1_1: 'Instituto de Estándares',
    hero_h1_2: 'Clínicos del Futuro',
    hero_sub: 'No es una mejora de cualificación, sino un reinicio completo del pensamiento clínico. Todos los médicos de LABS67 pasan por SLYAH.AI.',
    back: '← LABS67',
    hero_tag:'// SLYAH.AI · Grupo LABS67',
    btn1:'// Solicitar',
    btn2:'Programas →',
    stat1:'Tracks',
    stat2:'Herramientas',
    stat3:'Estándar',
    man_tag:'// Nuestro enfoque',
    man_title:'No es un curso.<br><span class="ac">Un reinicio.</span>',
    man_quote:'«Cada especialista del grupo LABS67 ha pasado por SLYAH.AI. No es una opción, es un estándar.»',
    pr1_num:'PRINCIPIO_01',
    pr1_t:'El paciente — centro del sistema',
    pr2_num:'PRINCIPIO_02',
    pr2_t:'La IA — herramienta, no sustituto',
    pr3_num:'PRINCIPIO_03',
    pr3_t:'El estándar — idéntico en todas partes',
    pr4_num:'PRINCIPIO_04',
    pr4_t:'La investigación — parte de la práctica',
    trk_tag:'// Programas',
    trk_title:'Tres <span class="ac">tracks</span>',
    trk_lead:'Cada track es un programa independiente con objetivos y resultados definidos.',
    t1_title:'Clinical Reboot',
    t2_title:'AI Integration Cert',
    t3_title:'R&D Lab',
    man_body:'Creamos el instituto porque hay pocos buenos médicos, no por falta de conocimientos sino de enfoque. SLYAH.AI cambia la forma en que un especialista piensa sobre el paciente, el proceso y la tecnología.',
    pr1_d:'Todos los protocolos se construyen en torno a la experiencia del paciente. No en torno a la comodidad del médico o la clínica.',
    pr2_d:'El médico decide. La IA garantiza precisión, velocidad y documentación. Enseñamos a trabajar con esta simbiosis.',
    pr3_d:'Un paciente en cualquier clínica del grupo recibe un nivel de atención idéntico. SLYAH.AI lo garantiza.',
    pr4_d:'Los mejores especialistas participan en el desarrollo de nuevos protocolos. Crecemos junto con nuestros médicos.',
    t1_d:'Reinicio completo de protocolos clínicos. Estándares de atención al paciente, documentación, interacción con el sistema de IA de la clínica. Obligatorio para todos los médicos del grupo.',
    t1_dur:'Duración: 2 semanas · Presencial + práctica',
    t2_d:'Certificación en herramientas de IA del grupo. Protocolos de voz, análisis de imágenes, interfaz de asistente. Práctica con equipamiento real de LABS67.',
    t2_dur:'Duración: 1 semana · Práctica',
    t3_d:'Para líderes de opinión y especialistas dispuestos a participar en el desarrollo de nuevos protocolos. Ensayos clínicos, publicaciones científicas, definición de estándares futuros.',
    t3_dur:'Duración: Por proyecto · Participación continua',
    who_tag:'// Para quién',
    who_title:'Quién llega a <span class="ac">SLYAH.AI</span>',
    who1_t:'Médicos de clínicas LABS67',
    who1_d:'Certificación obligatoria para todos los especialistas que trabajan bajo las marcas del grupo.',
    who2_t:'Equipos de franquicia',
    who2_d:'Los socios de LADZA.AI pasan por SLYAH.AI antes de la apertura — es parte del estándar del grupo.',
    who3_t:'Especialistas independientes',
    who3_d:'Médicos que quieren trabajar de otra manera — con tecnología, según estándares de nivel mundial.',
    who4_t:'Investigadores',
    who4_d:'Especialistas con experiencia, dispuestos a participar en I+D y en la creación de nuevos protocolos clínicos.',
    sb1_lbl:'// Garantía del grupo',
    sb1_t:'El certificado SLYAH.AI es una señal de que el especialista trabaja según los estándares LABS67.',
    sb1_s:'Los pacientes saben: si un médico está certificado por SLYAH.AI, están en buenas manos. Sin importar la ciudad o el país.',
    sb2_lbl:'// Para socios de LADZA.AI',
    sb2_t:'La formación del equipo está incluida en el paquete de soporte para la apertura de la clínica.',
    sb2_s:'Los franquiciados no gestionan solos la contratación y formación del personal — SLYAH.AI se encarga por completo.',
    app_tag:'// Solicitar',
    app_title:'Empiece <span class="ac">ahora</span>',
    app_lead:'La admisión es por solicitud. Prioridad: socios del grupo y especialistas independientes con más de 2 años de experiencia.',
    form_title:'// SOLICITUD DE FORMACIÓN',
    form_btn:'// ENVIAR SOLICITUD →',
    footer_sub:'Grupo LABS67',
    track1_tag:'TRACK_01 · BÁSICO',track2_tag:'TRACK_02 · TECNOLÓGICO',track3_tag:'TRACK_03 · INVESTIGACIÓN',
  },
  it: {nav_about:'Chi siamo',nav_programs:'Programmi',nav_who:'Per chi',nav_apply:'Candidati',logo_sub:'Gruppo LABS67',
    title: 'SLYAH.AI — Istituto di Standard Clinici · LABS67',
    nav_cta: 'Candidati',
    hero_h1_1: 'Istituto di Standard',
    hero_h1_2: 'Clinici del Futuro',
    hero_sub: 'Non un aggiornamento delle qualifiche — un riavvio completo del pensiero clinico. Tutti i medici LABS67 passano per SLYAH.AI.',
    back: '← LABS67',
    hero_tag:'// SLYAH.AI · Gruppo LABS67',
    btn1:'// Candidati',
    btn2:'Programmi →',
    stat1:'Percorsi',
    stat2:'Strumenti',
    stat3:'Standard',
    man_tag:'// Il nostro approccio',
    man_title:'Non un corso.<br><span class="ac">Un riavvio.</span>',
    man_quote:'«Ogni specialista del gruppo LABS67 è passato per SLYAH.AI. Non è un\'opzione — è uno standard.»',
    pr1_num:'PRINCIPIO_01',
    pr1_t:'Il paziente — centro del sistema',
    pr2_num:'PRINCIPIO_02',
    pr2_t:'L\'IA — strumento, non sostituto',
    pr3_num:'PRINCIPIO_03',
    pr3_t:'Lo standard — identico ovunque',
    pr4_num:'PRINCIPIO_04',
    pr4_t:'La ricerca — parte della pratica',
    trk_tag:'// Programmi',
    trk_title:'Tre <span class="ac">percorsi</span>',
    trk_lead:'Ogni percorso è un programma a sé con obiettivi e risultati chiari.',
    t1_title:'Clinical Reboot',
    t2_title:'AI Integration Cert',
    t3_title:'R&D Lab',
    man_body:'Abbiamo creato l\'istituto perché i buoni medici sono pochi — non per conoscenze, ma per approccio. SLYAH.AI cambia il modo in cui lo specialista pensa al paziente, al processo e alla tecnologia.',
    pr1_d:'Tutti i protocolli si costruiscono attorno all\'esperienza del paziente. Non attorno alla comodità del medico o della clinica.',
    pr2_d:'Il medico decide. L\'IA garantisce precisione, velocità e documentazione. Insegniamo a lavorare con questa simbiosi.',
    pr3_d:'Un paziente in qualsiasi clinica del gruppo riceve un livello di assistenza identico. SLYAH.AI lo garantisce.',
    pr4_d:'I migliori specialisti partecipano allo sviluppo di nuovi protocolli. Cresciamo insieme ai nostri medici.',
    t1_d:'Riavvio completo dei protocolli clinici. Standard di cura del paziente, documentazione, interazione con il sistema IA della clinica. Obbligatorio per tutti i medici del gruppo.',
    t1_dur:'Durata: 2 settimane · In presenza + pratica',
    t2_d:'Certificazione sugli strumenti IA del gruppo. Protocolli vocali, analisi di immagini, interfaccia assistente. Pratica su attrezzature reali LABS67.',
    t2_dur:'Durata: 1 settimana · Pratica',
    t3_d:'Per leader di opinione e specialisti pronti a partecipare allo sviluppo di nuovi protocolli. Sperimentazioni cliniche, pubblicazioni scientifiche, definizione degli standard futuri.',
    t3_dur:'Durata: Per progetto · Partecipazione continuativa',
    who_tag:'// Per chi',
    who_title:'Chi arriva ad <span class="ac">SLYAH.AI</span>',
    who1_t:'Medici delle cliniche LABS67',
    who1_d:'Certificazione obbligatoria per tutti gli specialisti che lavorano sotto i marchi del gruppo.',
    who2_t:'Team in franchising',
    who2_d:'I partner di LADZA.AI passano per SLYAH.AI prima dell\'apertura — fa parte dello standard del gruppo.',
    who3_t:'Specialisti indipendenti',
    who3_d:'Medici che vogliono lavorare diversamente — con la tecnologia, secondo standard di livello mondiale.',
    who4_t:'Ricercatori',
    who4_d:'Specialisti con esperienza, pronti a partecipare alla R&S e alla creazione di nuovi protocolli clinici.',
    sb1_lbl:'// Garanzia del gruppo',
    sb1_t:'Il certificato SLYAH.AI è il segno che lo specialista lavora secondo gli standard LABS67.',
    sb1_s:'I pazienti sanno: se un medico è certificato SLYAH.AI, sono in mani sicure. Indipendentemente dalla città o dal paese.',
    sb2_lbl:'// Per i partner LADZA.AI',
    sb2_t:'La formazione del team è inclusa nel pacchetto di supporto all\'apertura della clinica.',
    sb2_s:'I franchisee non gestiscono da soli il reclutamento e la formazione — SLYAH.AI se ne occupa interamente.',
    app_tag:'// Candidati',
    app_title:'Inizia <span class="ac">ora</span>',
    app_lead:'L\'ammissione avviene su candidatura. Priorità: partner del gruppo e specialisti indipendenti con oltre 2 anni di esperienza.',
    form_title:'// CANDIDATURA PER LA FORMAZIONE',
    form_btn:'// INVIA CANDIDATURA →',
    footer_sub:'Gruppo LABS67',
    track1_tag:'TRACK_01 · BASE',track2_tag:'TRACK_02 · TECNOLOGICO',track3_tag:'TRACK_03 · RICERCA',
  },
  pt: {nav_about:'Sobre nós',nav_programs:'Programas',nav_who:'Para quem',nav_apply:'Candidatar-se',logo_sub:'Grupo LABS67',
    title: 'SLYAH.AI — Instituto de Padrões Clínicos · LABS67',
    nav_cta: 'Candidatar-se',
    hero_h1_1: 'Instituto de Padrões',
    hero_h1_2: 'Clínicos do Futuro',
    hero_sub: 'Não é uma atualização de qualificação — é um reinício completo do pensamento clínico. Todos os médicos da LABS67 passam pela SLYAH.AI.',
    back: '← LABS67',
    hero_tag:'// SLYAH.AI · Grupo LABS67',
    btn1:'// Candidatar-se',
    btn2:'Programas →',
    stat1:'Trilhas',
    stat2:'Ferramentas',
    stat3:'Padrão',
    man_tag:'// Nossa abordagem',
    man_title:'Não é um curso.<br><span class="ac">Um reinício.</span>',
    man_quote:'«Cada especialista do grupo LABS67 passou pela SLYAH.AI. Não é uma opção — é um padrão.»',
    pr1_num:'PRINCÍPIO_01',
    pr1_t:'O paciente — centro do sistema',
    pr2_num:'PRINCÍPIO_02',
    pr2_t:'A IA — ferramenta, não substituto',
    pr3_num:'PRINCÍPIO_03',
    pr3_t:'O padrão — idêntico em todo lugar',
    pr4_num:'PRINCÍPIO_04',
    pr4_t:'A pesquisa — parte da prática',
    trk_tag:'// Programas',
    trk_title:'Três <span class="ac">trilhas</span>',
    trk_lead:'Cada trilha é um programa independente com objetivos e resultados claros.',
    t1_title:'Clinical Reboot',
    t2_title:'AI Integration Cert',
    t3_title:'R&D Lab',
    man_body:'Criamos o instituto porque bons médicos são raros — não por falta de conhecimento, mas de abordagem. A SLYAH.AI muda a forma como o especialista pensa sobre o paciente, o processo e a tecnologia.',
    pr1_d:'Todos os protocolos são construídos em torno da experiência do paciente. Não em torno da conveniência do médico ou da clínica.',
    pr2_d:'O médico decide. A IA garante precisão, velocidade e documentação. Ensinamos a trabalhar com essa simbiose.',
    pr3_d:'Um paciente em qualquer clínica do grupo recebe um nível de cuidado idêntico. A SLYAH.AI garante isso.',
    pr4_d:'Os melhores especialistas participam no desenvolvimento de novos protocolos. Crescemos junto com os nossos médicos.',
    t1_d:'Reinício completo dos protocolos clínicos. Padrões de atendimento ao paciente, documentação, interação com o sistema de IA da clínica. Obrigatório para todos os médicos do grupo.',
    t1_dur:'Duração: 2 semanas · Presencial + prática',
    t2_d:'Certificação nas ferramentas de IA do grupo. Protocolos de voz, análise de imagens, interface do assistente. Prática com equipamento real da LABS67.',
    t2_dur:'Duração: 1 semana · Prática',
    t3_d:'Para líderes de opinião e especialistas dispostos a participar no desenvolvimento de novos protocolos. Ensaios clínicos, publicações científicas, definição de padrões futuros.',
    t3_dur:'Duração: Por projeto · Participação contínua',
    who_tag:'// Para quem',
    who_title:'Quem vem à <span class="ac">SLYAH.AI</span>',
    who1_t:'Médicos das clínicas LABS67',
    who1_d:'Certificação obrigatória para todos os especialistas que trabalham sob as marcas do grupo.',
    who2_t:'Equipas de franquia',
    who2_d:'Os parceiros da LADZA.AI passam pela SLYAH.AI antes da abertura — faz parte do padrão do grupo.',
    who3_t:'Especialistas independentes',
    who3_d:'Médicos que querem trabalhar de forma diferente — com tecnologia, segundo padrões de nível mundial.',
    who4_t:'Investigadores',
    who4_d:'Especialistas com experiência, dispostos a participar em I&D e na criação de novos protocolos clínicos.',
    sb1_lbl:'// Garantia do grupo',
    sb1_t:'O certificado SLYAH.AI é sinal de que o especialista trabalha segundo os padrões LABS67.',
    sb1_s:'Os pacientes sabem: se um médico é certificado pela SLYAH.AI, estão em boas mãos. Independentemente da cidade ou do país.',
    sb2_lbl:'// Para parceiros LADZA.AI',
    sb2_t:'A formação da equipa está incluída no pacote de apoio à abertura da clínica.',
    sb2_s:'Os franqueados não gerem sozinhos o recrutamento e a formação — a SLYAH.AI encarrega-se disso por completo.',
    app_tag:'// Candidatar-se',
    app_title:'Comece <span class="ac">agora</span>',
    app_lead:'A admissão é por candidatura. Prioridade: parceiros do grupo e especialistas independentes com mais de 2 anos de experiência.',
    form_title:'// CANDIDATURA PARA FORMAÇÃO',
    form_btn:'// ENVIAR CANDIDATURA →',
    footer_sub:'Grupo LABS67',
    track1_tag:'TRACK_01 · BÁSICO',track2_tag:'TRACK_02 · TECNOLÓGICO',track3_tag:'TRACK_03 · PESQUISA',
  },
  ja: {nav_about:'私たちについて',nav_programs:'プログラム',nav_who:'対象者',nav_apply:'応募する',logo_sub:'LABS67グループ',
    title: 'SLYAH.AI — 臨床基準研究所 · LABS67',
    nav_cta: '応募する',
    hero_h1_1: '未来の臨床基準',
    hero_h1_2: '研究所',
    hero_sub: '資格の更新ではありません — 臨床思考の完全なリブートです。LABS67の全医師がSLYAH.AIを経験します。',
    back: '← LABS67',
    hero_tag:'// SLYAH.AI · LABS67グループ',
    btn1:'// 応募する',
    btn2:'プログラム →',
    stat1:'トラック',
    stat2:'ツール',
    stat3:'スタンダード',
    man_tag:'// 私たちのアプローチ',
    man_title:'コースではない。<br><span class="ac">リブート。</span>',
    man_quote:'「LABS67グループのすべての専門家がSLYAH.AIを経験しています。これはオプションではなく、スタンダードです。」',
    pr1_num:'原則_01',
    pr1_t:'患者 — システムの中心',
    pr2_num:'原則_02',
    pr2_t:'AI — ツールであり代替ではない',
    pr3_num:'原則_03',
    pr3_t:'基準 — どこでも同一',
    pr4_num:'原則_04',
    pr4_t:'研究 — 実践の一部',
    trk_tag:'// プログラム',
    trk_title:'3つの<span class="ac">トラック</span>',
    trk_lead:'各トラックは明確な目標と成果を持つ独立したプログラムです。',
    t1_title:'Clinical Reboot',
    t2_title:'AI Integration Cert',
    t3_title:'R&D Lab',
    man_body:'良い医師が少ないのは知識の問題ではなく、アプローチの問題です。SLYAH.AIは、専門家が患者、プロセス、テクノロジーについて考える方法を変えます。',
    pr1_d:'すべてのプロトコルは患者体験を中心に構築されます。医師やクリニックの利便性ではありません。',
    pr2_d:'医師が判断します。AIは精度、速度、記録を保証します。この共生関係での働き方を教えます。',
    pr3_d:'グループのどのクリニックでも患者は同一レベルのケアを受けます。SLYAH.AIがそれを保証します。',
    pr4_d:'最高の専門家が新しいプロトコルの開発に参加します。私たちは医師とともに成長します。',
    t1_d:'臨床プロトコルの完全なリブート。患者ケアの基準、記録、クリニックAIシステムとの連携。グループの全医師に必須。',
    t1_dur:'期間：2週間 · 対面 + 実習',
    t2_d:'グループのAIツールに関する認定。音声プロトコル、画像分析、アシスタントインターフェース。LABS67の実際の機器での実習。',
    t2_dur:'期間：1週間 · 実習',
    t3_d:'オピニオンリーダーや新プロトコル開発に参加する準備のある専門家向け。臨床試験、学術出版、将来の基準策定。',
    t3_dur:'期間：プロジェクトごと · 継続参加',
    who_tag:'// 対象者',
    who_title:'<span class="ac">SLYAH.AI</span>に来る人',
    who1_t:'LABS67クリニックの医師',
    who1_d:'グループブランドで働くすべての専門家に必須の認定。',
    who2_t:'フランチャイズチーム',
    who2_d:'LADZA.AIのパートナーは開業前にSLYAH.AIを修了します — グループ基準の一部です。',
    who3_t:'独立した専門家',
    who3_d:'テクノロジーを活用し、世界水準で働きたい医師。',
    who4_t:'研究者',
    who4_d:'R&Dや新臨床プロトコルの策定に参加する準備のある経験豊富な専門家。',
    sb1_lbl:'// グループの保証',
    sb1_t:'SLYAH.AIの認定証は、専門家がLABS67基準で働いている証です。',
    sb1_s:'患者は知っています：医師がSLYAH.AI認定であれば、安心して任せられます。都市や国を問わず。',
    sb2_lbl:'// LADZA.AIパートナー向け',
    sb2_t:'チームの研修はクリニック開業時のサポートパッケージに含まれています。',
    sb2_s:'フランチャイズパートナーは人材採用と研修を単独で行う必要はありません — SLYAH.AIが完全にカバーします。',
    app_tag:'// 応募する',
    app_title:'今すぐ<span class="ac">始めましょう</span>',
    app_lead:'入学は申請制です。優先：グループパートナーおよび2年以上の経験を持つ独立した専門家。',
    form_title:'// 研修申込',
    form_btn:'// 申請を送信 →',
    footer_sub:'LABS67グループ',
    track1_tag:'トラック_01 · 基礎',track2_tag:'トラック_02 · テクノロジー',track3_tag:'トラック_03 · 研究',
  },
  ko: {nav_about:'소개',nav_programs:'프로그램',nav_who:'대상',nav_apply:'지원하기',logo_sub:'LABS67 그룹',
    title: 'SLYAH.AI — 임상 표준 연구소 · LABS67',
    nav_cta: '지원하기',
    hero_h1_1: '미래의 임상 표준',
    hero_h1_2: '연구소',
    hero_sub: '자격 업그레이드가 아닙니다 — 임상 사고의 완전한 리부트입니다. LABS67의 모든 의사가 SLYAH.AI을 거칩니다.',
    back: '← LABS67',
    hero_tag:'// SLYAH.AI · LABS67 그룹',
    btn1:'// 지원하기',
    btn2:'프로그램 →',
    stat1:'트랙',
    stat2:'도구',
    stat3:'표준',
    man_tag:'// 우리의 접근',
    man_title:'코스가 아닙니다.<br><span class="ac">리부트.</span>',
    man_quote:'「LABS67 그룹의 모든 전문가가 SLYAH.AI을 거쳤습니다. 이것은 선택이 아닌 표준입니다.」',
    pr1_num:'원칙_01',
    pr1_t:'환자 — 시스템의 중심',
    pr2_num:'원칙_02',
    pr2_t:'AI — 도구이지 대체물이 아님',
    pr3_num:'원칙_03',
    pr3_t:'표준 — 어디서나 동일',
    pr4_num:'원칙_04',
    pr4_t:'연구 — 실무의 일부',
    trk_tag:'// 프로그램',
    trk_title:'3개의 <span class="ac">트랙</span>',
    trk_lead:'각 트랙은 명확한 목표와 성과를 가진 독립 프로그램입니다.',
    t1_title:'Clinical Reboot',
    t2_title:'AI Integration Cert',
    t3_title:'R&D Lab',
    man_body:'좋은 의사가 적은 것은 지식이 아니라 접근 방식의 문제입니다. SLYAH.AI은 전문가가 환자, 프로세스, 기술에 대해 사고하는 방식을 바꿉니다.',
    pr1_d:'모든 프로토콜은 환자 경험을 중심으로 구축됩니다. 의사나 클리닉의 편의가 아닙니다.',
    pr2_d:'의사가 결정합니다. AI는 정확성, 속도, 기록을 보장합니다. 이 공생 관계에서의 업무 방식을 가르칩니다.',
    pr3_d:'그룹의 어느 클리닉에서든 환자는 동일한 수준의 케어를 받습니다. SLYAH.AI이 이를 보장합니다.',
    pr4_d:'최고의 전문가들이 새로운 프로토콜 개발에 참여합니다. 우리는 의사들과 함께 성장합니다.',
    t1_d:'임상 프로토콜의 완전한 리부트. 환자 케어 표준, 기록, 클리닉 AI 시스템과의 상호작용. 그룹 내 모든 의사에게 필수.',
    t1_dur:'기간: 2주 · 대면 + 실습',
    t2_d:'그룹 AI 도구 인증. 음성 프로토콜, 이미지 분석, 어시스턴트 인터페이스. LABS67 실제 장비로 실습.',
    t2_dur:'기간: 1주 · 실습',
    t3_d:'오피니언 리더와 새 프로토콜 개발에 참여할 준비가 된 전문가 대상. 임상 시험, 학술 출판, 미래 표준 수립.',
    t3_dur:'기간: 프로젝트별 · 지속 참여',
    who_tag:'// 대상',
    who_title:'<span class="ac">SLYAH.AI</span>에 오는 사람들',
    who1_t:'LABS67 클리닉 의사',
    who1_d:'그룹 브랜드 하에 근무하는 모든 전문가를 위한 필수 인증.',
    who2_t:'프랜차이즈 팀',
    who2_d:'LADZA.AI 파트너는 개원 전에 SLYAH.AI을 이수합니다 — 그룹 표준의 일부입니다.',
    who3_t:'독립 전문가',
    who3_d:'기술을 활용하여 세계적 수준으로 일하고 싶은 의사.',
    who4_t:'연구자',
    who4_d:'R&D 및 새로운 임상 프로토콜 수립에 참여할 준비가 된 경험 있는 전문가.',
    sb1_lbl:'// 그룹 보증',
    sb1_t:'SLYAH.AI 인증서는 전문가가 LABS67 표준에 따라 근무한다는 증표입니다.',
    sb1_s:'환자는 알고 있습니다: 의사가 SLYAH.AI 인증이라면 안심할 수 있습니다. 도시나 국가에 관계없이.',
    sb2_lbl:'// LADZA.AI 파트너용',
    sb2_t:'팀 교육은 클리닉 개원 시 지원 패키지에 포함되어 있습니다.',
    sb2_s:'프랜차이즈 파트너는 인력 채용과 교육을 혼자 하지 않습니다 — SLYAH.AI이 완전히 담당합니다.',
    app_tag:'// 지원하기',
    app_title:'지금 <span class="ac">시작하세요</span>',
    app_lead:'입학은 지원제입니다. 우선: 그룹 파트너 및 2년 이상 경력의 독립 전문가.',
    form_title:'// 교육 신청',
    form_btn:'// 신청서 제출 →',
    footer_sub:'LABS67 그룹',
    track1_tag:'트랙_01 · 기본',track2_tag:'트랙_02 · 기술',track3_tag:'트랙_03 · 연구',
  },
};
const LANG_FLAGS = {
  be:`<rect width="18" height="4" fill="#fff"/><rect y="4" width="18" height="4" fill="#CF101A"/><rect y="8" width="18" height="4" fill="#fff"/>`,
  uk:`<rect width="18" height="6" fill="#005BBB"/><rect y="6" width="18" height="6" fill="#FFD500"/>`,
  en:`<rect width="18" height="12" fill="#012169"/><path d="M0,0 L18,12 M18,0 L0,12" stroke="#fff" stroke-width="2"/><rect x="7" width="4" height="12" fill="#fff"/><rect y="4" width="18" height="4" fill="#fff"/><rect x="8" width="2" height="12" fill="#C8102E"/><rect y="5" width="18" height="2" fill="#C8102E"/>`,
  pl:`<rect width="18" height="6" fill="#fff"/><rect y="6" width="18" height="6" fill="#DC143C"/>`,
  fr:`<rect width="6" height="12" fill="#002395"/><rect x="6" width="6" height="12" fill="#fff"/><rect x="12" width="6" height="12" fill="#ED2939"/>`,
  de:`<rect width="18" height="4" fill="#000"/><rect y="4" width="18" height="4" fill="#DD0000"/><rect y="8" width="18" height="4" fill="#FFCE00"/>`,
  ru:`<rect width="18" height="4" fill="#fff"/><rect y="4" width="18" height="4" fill="#0039A6"/><rect y="8" width="18" height="4" fill="#fff"/>`,
  es:`<rect width="18" height="3" fill="#AA151B"/><rect y="3" width="18" height="6" fill="#F1BF00"/><rect y="9" width="18" height="3" fill="#AA151B"/>`,
  it:`<rect width="6" height="12" fill="#009246"/><rect x="6" width="6" height="12" fill="#fff"/><rect x="12" width="6" height="12" fill="#CE2B37"/>`,
  pt:`<rect width="7" height="12" fill="#006600"/><rect x="7" width="11" height="12" fill="#FF0000"/><circle cx="7" cy="6" r="2.5" fill="#FF0" stroke="#006600" stroke-width="0.3"/>`,
  ja:`<rect width="18" height="12" fill="#fff"/><circle cx="9" cy="6" r="3.2" fill="#BC002D"/>`,
  ko:`<rect width="18" height="12" fill="#fff"/><circle cx="9" cy="6" r="3" fill="#CD2E3A"/><path d="M9,6 a1.5,1.5 0 0,1 0,3 a1.5,1.5 0 0,0 0,-3" fill="#0047A0"/><path d="M9,3 a1.5,1.5 0 0,0 0,3 a1.5,1.5 0 0,1 0,-3" fill="#0047A0"/>`
};
